#!/bin/bash

#Provide the name of the project as used in Lean Euler
PROJECT_NAME=$1

#Go to the PWE-directory with all the relevant python files
cd ../Clingo\ Parser/

#Run clingo on the file generated by Lean Euler. It goes to the Lean Euler directory and finds the clingo file named $PROJECT_NAME.lp4 and runs clingo on it
python run_clingo.py ../../LeanEuler/Clingo_Input_Files/$PROJECT_NAME.lp4 $PROJECT_NAME

#Parse the clingo output and store the produced Pandas Dataframes
python load_worlds.py $PROJECT_NAME

#Export the dataframes to sql and csv formats
python export.py -p $PROJECT_NAME -csv -sql

#Need to run this to use the visualisation script. Calls a dummy distance function which does no computation.
python dist_calc.py -p $PROJECT_NAME -custom_dist_func dummy_dist_func -calc_dist_matrix

#Produce the visualisations for the generated PWs. Stores these in Mini Workflow/parser_output/euler_visualizations/$PROJECT_NAME/
python visualize.py -p $PROJECT_NAME -custom_visualisation_func euler_visualization
