{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,blue)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,green)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,blue), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,green), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,blue), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,green), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,blue), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,green), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,blue), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,green), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,blue), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,green), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
{color(france,red), color(belgium,red), color(luxembourg,red), color(germany,red), color(netherlands,red), color(denmark,red)}
